import React, { useState } from 'react';
import { eligibilityTables, CATEGORY_LABELS, PHASE_LABELS, ELIGIBILITY_COMPLIANCE_NOTE } from '../evidence/eligibilityTables.js';
const statusText = { enrolling: 'Recruiting at recorded check', soon: 'Not yet recruiting at recorded check', closed: 'Closed to enrollment in stored profile', unverified: 'Unverified' };
const escHtml = value => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const escMd = value => String(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
export function buildTableMarkdown(table) {
  return `## ${table.title}\n\n| Study | Summary | Inclusion criteria | Exclusion criteria |\n| --- | --- | --- | --- |\n` + table.trials.map(trial => `| ${escMd(trial.acronym)} ${escMd(trial.nct)} · ${escMd(statusText[trial.status])} · recorded check ${trial.sourceDate || 'not recorded'} | ${escMd(trial.summary)} | ${escMd(trial.eligibility.join('; '))} | ${escMd(trial.exclusions.join('; '))} |`).join('\n') + `\n\n${ELIGIBILITY_COMPLIANCE_NOTE}`;
}
export function buildTableHtml(table) {
  return `<section><h2>${escHtml(table.title)}</h2><table><thead><tr><th>Study</th><th>Summary</th><th>Inclusion criteria</th><th>Exclusion criteria</th></tr></thead><tbody>` + table.trials.map(trial => `<tr><td>${escHtml(trial.acronym)} ${escHtml(trial.nct)}<p>${escHtml(statusText[trial.status])}; recorded check ${trial.sourceDate || 'not recorded'}</p>${trial.href ? `<a href="${escHtml(trial.href)}">Registry record</a>` : ''}</td><td>${escHtml(trial.summary)}</td><td><ul>${trial.eligibility.map(line => `<li>${escHtml(line)}</li>`).join('')}</ul></td><td><ul>${trial.exclusions.map(line => `<li>${escHtml(line)}</li>`).join('')}</ul></td></tr>`).join('') + `</tbody></table><p>${escHtml(ELIGIBILITY_COMPLIANCE_NOTE)}</p></section>`;
}
export function EligibilityTables({ copyToClipboard }) {
  const [category, setCategory] = useState('ischemic');
  return <div className="space-y-4"><div className="flex flex-wrap gap-2" role="group" aria-label="Stroke category filter">{Object.entries(CATEGORY_LABELS).map(([id, label]) => <button key={id} type="button" aria-pressed={category === id} className="min-h-[44px] rounded-md border border-line px-4 font-semibold" onClick={() => setCategory(id)}>{label}</button>)}</div><p className="text-sm text-mute">The same full stored criteria appear in the study database. The two table-only reference profiles are retained with their separate source limitations.</p>{eligibilityTables.filter(table => table.category === category).map(table => <details key={table.id} open={table.phase === 'acute'} className="rounded-lg border border-line bg-card p-4"><summary className="min-h-[44px] cursor-pointer font-bold">{PHASE_LABELS[table.phase]} · {table.trials.length} studies</summary><div className="space-y-4">{table.trials.map(trial => <article key={trial.acronym} className="border-t border-line pt-3"><h3 className="font-bold">{trial.acronym} {trial.nct && <a href={trial.href} target="_blank" rel="noopener noreferrer" className="text-link-600 underline">{trial.nct} ↗</a>}</h3><p className="text-sm text-mute">{statusText[trial.status]}. Recorded registry check: {trial.sourceDate || 'not recorded in this table'}. Local activation is not confirmed.</p><p className="mt-2 text-sm">{trial.summary}</p>{[['Inclusion criteria', trial.eligibility], ['Exclusion criteria', trial.exclusions]].map(([label, lines]) => <div key={label} className="mt-2"><h4 className="text-sm font-semibold">{label}</h4><ul className="list-disc space-y-1 pl-5 text-sm">{lines.map((line, i) => <li key={i}>{line}</li>)}</ul></div>)}{trial.sourceGaps?.length > 0 && <details className="mt-2"><summary className="min-h-[44px] cursor-pointer text-sm">Source gaps / confirmation required</summary><ul className="list-disc pl-5 text-sm">{trial.sourceGaps.map((line, i) => <li key={i}>{line}</li>)}</ul></details>}</article>)}</div><div className="mt-3 flex flex-wrap gap-3">{[['HTML', buildTableHtml], ['Markdown', buildTableMarkdown]].map(([format, build]) => <button key={format} type="button" className="min-h-[44px] rounded-md border border-line px-3 text-sm font-semibold" onClick={() => copyToClipboard?.(build(table), `${table.title} (${format})`)}>Copy as {format}</button>)}</div></details>)}</div>;
}
export default EligibilityTables;
