#!/usr/bin/env node
// Pre-compresses bundled assets to .gz (and .br when zlib supports it)
// so a static host (e.g. GitHub Pages with brotli, or nginx) can serve the
// pre-compressed file directly. Runs after `npm run build`.
//
// Safe no-op on CI systems without brotli support — gzip is always emitted.

import { promises as fs } from 'node:fs';
import { gzip, brotliCompress, constants as zlibConstants } from 'node:zlib';
import { promisify } from 'node:util';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { atomicWriteFile } from './atomic-write.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const gzipAsync = promisify(gzip);
const brotliAsync = promisify(brotliCompress);

const TARGETS = [
  'app.js',
  'tailwind.css',
  'index.html',
  'manifest.json',
  'service-worker.js',
  'app-assets.json'
];

async function fileSize(p) {
  try {
    const s = await fs.stat(p);
    return s.size;
  } catch {
    return null;
  }
}

async function compressGzip(bytes, dest) {
  await atomicWriteFile(dest, await gzipAsync(bytes, { level: 9 }));
}

async function compressBrotli(bytes, dest) {
  const compressed = await brotliAsync(bytes, {
    params: {
      [zlibConstants.BROTLI_PARAM_QUALITY]: 11
    }
  });
  await atomicWriteFile(dest, compressed);
}

async function main() {
  // The manifest is generated by build-browser, so compression follows every
  // hashed chunk without accidentally including stale files in the directory.
  const manifest = JSON.parse(await fs.readFile(path.join(ROOT, 'app-assets.json'), 'utf8'));
  const targets = [...new Set([...TARGETS, ...manifest.files.map(file => file.path)])];
  let ok = 0;
  let skipped = 0;
  for (const rel of targets) {
    const src = path.join(ROOT, rel);
    const size = await fileSize(src);
    if (size == null) {
      skipped += 1;
      console.log(`skip ${rel} (not found)`);
      continue;
    }
    if (size < 512) {
      // Not worth compressing
      skipped += 1;
      continue;
    }
    // Concurrent build/test readers must see either the previous complete
    // artifact or its complete replacement, never an opened/truncated stream.
    // Both encodings use the same source snapshot.
    const bytes = await fs.readFile(src);
    await compressGzip(bytes, `${src}.gz`);
    await compressBrotli(bytes, `${src}.br`);
    const gzSize = await fileSize(`${src}.gz`);
    const brSize = await fileSize(`${src}.br`);
    const pct = (n) => (n != null ? `${((n / size) * 100).toFixed(1)}%` : 'n/a');
    console.log(`ok   ${rel.padEnd(20)} ${size}B → gz ${gzSize}B (${pct(gzSize)}), br ${brSize}B (${pct(brSize)})`);
    ok += 1;
  }
  console.log(`\nCompressed ${ok} file(s), skipped ${skipped}.`);
}

main().catch((err) => {
  console.error('compress-assets failed:', err);
  process.exit(1);
});
