// src/content-context.js
//
// Runtime access + workflow-context filtering for the /content data layer.
//
// This is the reusable primitive the Telestroke / Inpatient / Clinic context
// switch is built on, and the seam through which the Guidelines & References
// and Education surfaces become data-driven. It is a PURE module (no React, no
// DOM) so it unit-tests without a browser and tree-shakes cleanly — it is not
// yet imported by app.jsx (see REMAINING-WORK.md for the wiring step).
//
// Data source: content/bundle.json (generated by scripts/build-content-bundle.mjs
// from the authored /content files).

import bundle from '../content/bundle.json';

export const WORKFLOW_CONTEXTS = ['telestroke', 'inpatient', 'clinic'];

// Map a content record's own audience field(s) to the workflow-context axis.
// - education records carry an explicit `contexts` array.
// - guideline recommendations carry a `setting` (inpatient|outpatient|
//   pre-facility|all) that projects onto the workflow axis.
// - everything else is treated as relevant to all contexts unless it opts in
//   via a `contexts` array. Defaulting to "all" is deliberate: filtering must
//   never hide clinically relevant content the author did not explicitly scope.
const SETTING_TO_CONTEXTS = {
  inpatient: ['inpatient'],
  outpatient: ['clinic'],
  'pre-facility': ['telestroke'],
  all: ['telestroke', 'inpatient', 'clinic'],
};

export function contextsForRecord(rec) {
  if (Array.isArray(rec.contexts) && rec.contexts.length) {
    return rec.contexts.filter((c) => WORKFLOW_CONTEXTS.includes(c));
  }
  if (rec.setting && SETTING_TO_CONTEXTS[rec.setting]) {
    return SETTING_TO_CONTEXTS[rec.setting];
  }
  return [...WORKFLOW_CONTEXTS];
}

// True if a record is relevant to `context`. A null/undefined context (the
// "All" pill, or global search) matches everything.
export function isRelevantTo(rec, context) {
  if (!context) return true;
  if (!WORKFLOW_CONTEXTS.includes(context)) return true;
  return contextsForRecord(rec).includes(context);
}

// Filter a list by context, preserving order. `null` context → unchanged (this
// is what keeps global search unfiltered).
export function filterByContext(items, context) {
  if (!context) return items.slice();
  return items.filter((rec) => isRelevantTo(rec, context));
}

// ── Domain accessors (optionally context-scoped) ──────────────────────────
const clone = (arr) => arr.map((r) => ({ ...r }));

export function getGuidelines(context = null) { return filterByContext(bundle.guidelines || [], context); }
export function getTrials(context = null) { return filterByContext(bundle.trials || [], context); }
export function getEducation(context = null) { return filterByContext(bundle.education || [], context); }
export function getReferences(context = null) { return filterByContext(bundle.references || [], context); }
// Calculators are relevant across contexts; the registry is returned whole and
// callers reorder/surface by category. Kept as an accessor for symmetry.
export function getCalculators(context = null) { return filterByContext(bundle.calculators || [], context); }

export function getCalculatorById(id) {
  return (bundle.calculators || []).find((c) => c.id === id) || null;
}

// Everything, flattened with a `domain` tag — the single index the command
// palette / global search consumes so search spans all data sources at once.
export function getSearchIndex() {
  const out = [];
  const push = (domain, arr, toSearchable) => {
    for (const rec of arr || []) out.push({ domain, ...toSearchable(rec), record: rec });
  };
  push('guideline', bundle.guidelines, (r) => ({ id: r.id, title: r.statement, subtitle: `${r.guideline} · ${r.COR}/${r.LOE}`, keywords: r.section }));
  push('trial', bundle.trials, (r) => ({ id: r.id, title: r.name, subtitle: r.finding, keywords: r.category }));
  push('education', bundle.education, (r) => ({ id: r.id, title: r.title, subtitle: r.summary, keywords: (r.tags || []).join(' ') }));
  push('calculator', bundle.calculators, (r) => ({ id: r.id, title: r.name, subtitle: r.category, keywords: r.fn }));
  push('reference', bundle.references, (r) => ({ id: r.id, title: r.title, subtitle: r.category, keywords: r.type }));
  return out;
}

export function searchContent(query, context = null) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return [];
  const scoped = getSearchIndex().filter((e) => isRelevantTo(e.record, context));
  return scoped.filter((e) =>
    [e.title, e.subtitle, e.keywords, e.id].filter(Boolean).some((s) => String(s).toLowerCase().includes(q))
  );
}

export const contentMeta = bundle._meta;
export { clone as _cloneForTest };
