import React from 'react';
import EncounterTimeline from './components/EncounterTimeline.jsx';
import TimestampNowButton from './components/TimestampNowButton.jsx';
import { localTimestamp } from './encounter-timeline.js';
import TiaReadiness from './components/TiaReadiness.jsx';
import EncounterDetails from './components/EncounterDetails.jsx';
import { MRS_OPTIONS, weightInKg, displayWeight, nihssKeyboardOption } from './encounter-inputs.js';
import { DOCUMENT_FORMATS, documentationLabel } from './documentation-output.js';
import { focusEncounterTarget } from './encounter-overview.js';
import EncounterOverview, { EncounterNavigation } from './components/EncounterOverview.jsx';
import { DOCUMENTATION_PROMPTS, appendDocumentationPrompt } from './documentation-prompts.js';
import { NIHSS_ITEMS } from './clinical/nihss-items.js';
import { SAFETY_ITEMS } from './clinical/safety-items.js';
import { getClinicalClaim } from './clinical/claim-registry.js';
import { MTICI_DESCRIPTORS } from './supplementary-calculators.js';
import { calculateTNKDoseReviewed, calculateAlteplaseDoseReviewed, calculateCrClReviewed, calculateICHVolumeReviewed, calculateICHScore } from './calculators.js';
import { evaluateVideoTreatment, evaluateWakeUpScreen, assessAnticoagulantExposure, numericInput, reviewedGcs } from './encounter-clinical-review.js';
import { evaluateDAWN, evaluateDEFUSE3, evaluateLargeCoreEVT, recommendAcuteDAPT, computeNeurocheckSchedule } from './calculators-extended.js';
import { setEncounterReviewedScore, activeNote, DIAGNOSES, encounterVolume, encounterTiming, encounterNihss, validTimestamp, outputWarnings, buildSummary, daptReperfusionReview } from './workspace-state.js';

const UNKNOWN = [['', 'Not assessed'], ['true', 'Yes'], ['false', 'No']];
export function Field({ label, value, onChange, options, type = 'text', ...props }) {
  return <label className="workspace-field"><span>{label}</span>{options ? <select aria-label={label} value={value ?? ''} onChange={e => onChange(e.target.value)} {...props}>{options.map(([v, text]) => <option key={String(v)} value={v}>{text}</option>)}</select> : <input aria-label={label} value={value ?? ''} type={type} onChange={e => onChange(e.target.value)} {...props} />}</label>;
}
const NumberField = props => <Field type="number" step="any" {...props} />;
function TimestampField({ label, value, onChange, shortcut }) {
  const displayed = /(?:Z|[+-]\d{2}:\d{2})$/.test(value) && Number.isFinite(Date.parse(value)) ? localTimestamp(Date.parse(value)) : value;
  return <div><Field label={label} value={displayed} type="datetime-local" step="1" onChange={onChange} /><TimestampNowButton label={shortcut} hasValue={Boolean(value)} onUseNow={instant => onChange(new Date(instant).toISOString())} /></div>;
}
const Truth = ({ label, value, onChange }) => <Field label={label} value={typeof value === 'boolean' ? String(value) : ''} options={UNKNOWN} onChange={v => onChange(v === '' ? undefined : v === 'true')} />;
const TextField = ({ label, value, onChange, id }) => <label className="workspace-field"><span>{label}</span><textarea id={id} aria-label={label} rows={3} value={value || ''} onChange={e => onChange(e.target.value)} /></label>;
export function SourceLimits({ claim, url, label, children }) {
  const record = claim ? getClinicalClaim(claim) : null;
  return <details className="source-limits"><summary>Source / limits</summary>{record ? <><p>{record.population}</p><p>{record.limits}</p><p>{record.reviewScope} Recorded review: {record.reviewedAt}.</p><a href={record.sourceUrl} target="_blank" rel="noopener noreferrer">{record.sourceLabel}</a>{record.sources?.filter(s => s.url !== record.sourceUrl).map(s => <p key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label}</a></p>)}</> : <><p>{children}</p><a href={url} target="_blank" rel="noopener noreferrer">{label}</a><p>Existing source retained; no new comprehensive clinical review is implied.</p></>}</details>;
}
function Section({ step, title, id, children }) {
  return <section className="workflow-section" aria-labelledby={`${id}-title`} id={id}><h2 id={`${id}-title`} tabIndex={-1}><span aria-hidden="true">{String(step).padStart(2, '0')}</span> {title}</h2>{children}</section>;
}
function Result({ children }) { return <p className="workspace-result" role="status">{children}</p>; }
function EncounterCalculators({ state }) {
  const diagnosis = state.note.diagnosisCategory, followUp = state.context === 'follow-up';
  const contextual = diagnosis === 'sah' ? [['hunt-hess','Hunt–Hess'],['wfns','WFNS'],['modified-fisher','Modified Fisher'],['phases','PHASES']]
    : diagnosis === 'ich' ? [['ich-volume','ICH volume'],['ich-score','ICH severity']]
    : diagnosis === 'tia' ? [['abcd2','ABCD²'],['nascet','NASCET'],['chadsvasc','CHA₂DS₂-VASc'],['has-bled','HAS-BLED']]
    : diagnosis === 'ischemic' ? followUp ? [['rope','RoPE'],['pascal','PASCAL'],['nascet','NASCET'],['chadsvasc','CHA₂DS₂-VASc'],['has-bled','HAS-BLED']]
      : [['aspects-regions','ASPECTS'],['pc-aspects-regions','pc-ASPECTS'],['mtici','mTICI'],['nascet','NASCET']] : [];
  const links = [['gcs','GCS'],['crcl','Renal calculation'],['mrs-descriptors','mRS descriptors'],...contextual,...(followUp ? [['phq2','PHQ-2'],['stop-bang','STOP-BANG']] : [])];
  return <details><summary>Calculators for this encounter</summary><nav aria-label="Encounter calculators"><ul className="tool-links">{links.map(([id,label]) => <li key={id}><a href={`#/encounter/${id}`}>{label}</a></li>)}<li><a href="#/tools">All calculators</a></li></ul></nav></details>;
}

export default function Encounter({ state: s, update, now, onGenerate, onCopy, copyStatus, onReset }) {
  const n = s.note, active = activeNote(s), exam = encounterNihss(s), timing = encounterTiming(n, now);
  const documentLabel = documentationLabel(s);
  const note = (key, value) => update(prev => ({ ...prev, note: { ...prev.note, [key]: value } }));
  const group = (name, key, value) => update(prev => ({ ...prev, [name]: { ...prev[name], [key]: value } }));
  const nested = (key, value) => note('wakeUpStrokeWorkflow', { ...n.wakeUpStrokeWorkflow, [key]: value });
  const setClockNow = (prefix, instant) => {
    const value = localTimestamp(instant), [date, time] = value.split('T');
    update(prev => ({ ...prev, note: { ...prev.note, [`${prefix}Date`]: date, [`${prefix}Time`]: time, [`${prefix}Clock`]: { value, instant: new Date(instant).toISOString() } } }));
  };
  const acuteIschemic = s.context === 'acute' && n.diagnosisCategory === 'ischemic';
  const gcs = reviewedGcs(s.gcs);
  const volume = encounterVolume(s.volume);
  const age = numericInput(n.age, { min: 0, max: 120 });
  const ich = n.diagnosisCategory === 'ich' && age !== null && gcs !== null && volume && typeof s.ich.ivh === 'boolean' && typeof s.ich.infratentorial === 'boolean' ? calculateICHScore({ gcs: gcs <= 4 ? 'gcs34' : gcs <= 12 ? 'gcs512' : 'gcs1315', age80: age >= 80, volume30: volume.isLarge, ivh: s.ich.ivh, infratentorial: s.ich.infratentorial, criteriaReviewed: true }) : null;
  const renal = calculateCrClReviewed(n.age, n.weight, n.sex, n.creatinine, n.heightCm);
  const dose = acuteIschemic && s.drug ? s.drug === 'TNK' ? calculateTNKDoseReviewed(n.weight, s.doseAuthority) : calculateAlteplaseDoseReviewed(n.weight) : null;
  const safetyMissing = SAFETY_ITEMS.filter(item => typeof n.tnkContraindicationChecklist[item.id] !== 'boolean');
  const concerns = SAFETY_ITEMS.filter(item => n.tnkContraindicationChecklist[item.id] === true);
  const screenNote = { ...active, ivtContraindicationsReviewed: n.ivtContraindicationsReviewed && safetyMissing.length === 0 };
  const screen = acuteIschemic ? evaluateVideoTreatment({ note: screenNote, clock: timing.clock ? { total: timing.hours, label: timing.label } : null, aspects: s.aspects, pcAspects: s.pcAspects, now: new Date(now) }) : null;
  const exposure = acuteIschemic ? assessAnticoagulantExposure(active, new Date(now)) : null;
  const wake = acuteIschemic ? evaluateWakeUpScreen(active, new Date(now)) : null;
  const administration = acuteIschemic && s.actions.administered && s.drug && validTimestamp(s.actions.administrationTime, now);
  const schedule = administration ? computeNeurocheckSchedule(s.actions.administrationTime) : null;
  const nextCheck = schedule?.checks.find(check => check.at.getTime() > now);
  const daptConcern = ['currentICH', 'activeInternalBleeding', 'lowPlatelets', 'knownBleedingDiathesis', 'recentGIGUBleeding'].some(k => n.tnkContraindicationChecklist[k] === true);
  const reperfusionReview = daptReperfusionReview(s);
  const dapt = s.context === 'acute' && ['ischemic', 'tia'].includes(n.diagnosisCategory) ? recommendAcuteDAPT({ ...s.dapt, ichRisk: daptConcern ? 'high' : s.dapt.ichRisk, strokeType: n.diagnosisCategory, nihss: exam.total, timeFromOnsetH: timing.hours, hemorrhageExcluded: n.ctHemorrhageStatus === 'absent', reperfusionExcluded: reperfusionReview.excluded }) : null;
  const warning = outputWarnings(s);
  return <div className="encounter-workflow" id="tabpanel-encounter">
    <div className="workspace-heading"><h1>Encounter</h1><button type="button" className="workspace-secondary-action" onClick={onReset}>New encounter</button></div>
    <fieldset className="consultation-switch"><legend className="sr-only">Consultation</legend>{[['phone', 'Telephone'], ['video', 'Video']].map(([value, label]) => <label key={value}><input type="radio" name="consultation" value={value} checked={s.consultationType === value} onChange={() => update(prev => ({ ...prev, consultationType: value }))} /><span>{label}</span></label>)}</fieldset>
    <EncounterOverview state={s} now={now} />
    <EncounterNavigation />
    <EncounterCalculators state={s} />
    <Section step="1" id="context" title="Context, baseline & timing">
      <div className="field-grid">
        <Field label="Context" value={s.context} options={[[ 'acute', 'Acute consultation' ], ['follow-up', 'Follow-up / review']]} onChange={v => update({ ...s, context: v })} />
        <Field id="input-diagnosis" label="Working diagnosis" value={n.diagnosisCategory} options={[[ '', 'Not documented' ], ...Object.entries(DIAGNOSES)]} onChange={v => note('diagnosisCategory', v)} />
        <Field label="Sex" value={n.sex} options={[[ '', 'Not documented' ], ['M', 'Male'], ['F', 'Female']]} onChange={v => note('sex', v)} />
        <NumberField id="input-age" label="Age (years)" value={n.age} min="0" max="120" onChange={v => note('age', v)} />
        <NumberField id="input-weight" label={s.weightUnit === 'lb' ? 'Weight (lb)' : 'Weight (kg)'} value={displayWeight(n.weight, s.weightUnit)} min="0" max={s.weightUnit === 'lb' ? 771.62 : 350} onChange={value => note('weight', weightInKg(value, s.weightUnit))} />
        <Field label="Weight unit" value={s.weightUnit || 'kg'} options={[[ 'kg', 'kg' ], ['lb', 'lb']]} onChange={value => update(prev => ({ ...prev, weightUnit: value }))} />
        <Field id="calc-mrs" label="Baseline mRS" value={n.premorbidMRS} options={MRS_OPTIONS} onChange={v => note('premorbidMRS', v)} />
      </div>
      <details><summary>History & note details</summary><div className="field-grid"><Field label="Chief complaint" value={n.chiefComplaint} onChange={v => note('chiefComplaint', v)} /><TextField label="Presenting symptoms / HPI" value={n.symptoms} onChange={v => note('symptoms', v)} /><TextField label="Relevant past medical history" value={n.pmh} onChange={v => note('pmh', v)} /><TextField label="Medication reconciliation notes" value={n.medications} onChange={v => note('medications', v)} /><Field label="Clinician name" value={n.clinicianName} onChange={v => note('clinicianName', v)} /></div></details>
      <EncounterDetails section="context" state={s} update={update} />
      <EncounterTimeline state={s} update={update} now={now} />
      <label className="workspace-check"><input type="checkbox" checked={n.lkwUnknown} onChange={e => note('lkwUnknown', e.target.checked)} /> Last known well is unknown</label>
      {!n.lkwUnknown && <><div className="field-grid"><Field id="input-lkw-date" label="LKW date (local)" type="date" value={n.lkwDate} onChange={v => note('lkwDate', v)} /><Field label="LKW time (local)" type="time" step="1" value={n.lkwTime} onChange={v => note('lkwTime', v)} /></div><TimestampNowButton label="LKW" hasValue={Boolean(n.lkwDate || n.lkwTime)} onUseNow={instant => setClockNow('lkw', instant)} /></>}
      {n.lkwUnknown && <p className="workspace-help">Discovery records recognition, not onset. Retained LKW values are inactive while unknown is selected.</p>}
      <details><summary>Discovery / wake-up details</summary><div className="field-grid"><Field label="Discovery date (local)" type="date" value={n.discoveryDate} onChange={v => note('discoveryDate', v)} /><Field label="Discovery time (local)" type="time" step="1" value={n.discoveryTime} onChange={v => note('discoveryTime', v)} />{acuteIschemic && <Field label="Sleep midpoint (local)" type="datetime-local" value={n.wakeUpStrokeWorkflow.sleepMidpoint || ''} onChange={v => nested('sleepMidpoint', v)} />}</div><TimestampNowButton label="Discovery" hasValue={Boolean(n.discoveryDate || n.discoveryTime)} onUseNow={instant => setClockNow('discovery', instant)} /></details>
      <Result>{timing.invalid ? 'Invalid, future or skipped local-calendar time: correct the timestamp.' : timing.clock ? `${timing.label}: ${timing.clock.elapsedMinutes} min elapsed${n.lkwUnknown ? '' : ` · 4.5 h reference ${timing.clock.toLytic} · 24 h reference ${timing.clock.toLateEvt}`}` : `${timing.label} timestamp not documented`}</Result>
      <p className="workspace-help">Time references do not determine treatment eligibility. Local times repeated during a DST change require explicit clinician reconciliation.</p>
    </Section>
    <Section step="2" id="exam" title="Examination & imaging">
      <div id="calc-nihss" tabIndex={-1} className="tool-target"><h3>NIHSS</h3><Field id="input-nihss-source" label="Current NIHSS source" value={exam.source} options={[['itemized', 'Itemized examination'], ['reported', 'Reported total']]} onChange={v => update(prev => ({ ...prev, nihssSource: v }))} /><Result>{exam.source === 'reported' ? exam.complete ? `Reported NIHSS: ${exam.total}/42` : 'Reported total missing or invalid; enter a whole number from 0 to 42.' : exam.complete ? `Complete NIHSS: ${exam.total}/42` : `${exam.count}/15 items documented · partial sum ${exam.partial} · examination incomplete`}</Result>{exam.source === 'reported' ? <NumberField id="input-reported-nihss" label="Reported NIHSS total (0–42)" value={s.reportedNihss} min="0" max="42" step="1" onChange={v => update(prev => ({ ...prev, reportedNihss: v }))} /> : <details><summary>Enter NIHSS items</summary><p className="workspace-help">Number keys score and advance. Use U for not testable where available.</p><div className="field-grid">{NIHSS_ITEMS.map((item, index) => <Field onKeyDown={event => { if (event.altKey || event.ctrlKey || event.metaKey) return; const value = nihssKeyboardOption(item, event.key); if (!value) return; event.preventDefault(); group('nihss', item.id, value); if (index < NIHSS_ITEMS.length - 1) focusEncounterTarget(`nihss-${NIHSS_ITEMS[index + 1].id}`); }} key={item.id} id={`nihss-${item.id}`} label={item.name} value={s.nihss[item.id] || ''} options={[[ '', 'Not assessed' ], ...item.options.map(o => [o, o])]} onChange={v => group('nihss', item.id, v)} />)}</div></details>}<p className="workspace-help">Only the selected source supplies the current score. Switching sources preserves both entries.</p><SourceLimits url="https://www.ninds.nih.gov/health-information/stroke/assess-and-treat/nih-stroke-scale" label="NIH Stroke Scale, NINDS">Existing 15-item entry definition. Untestable or missing items prevent an itemized total. A reported total does not document individual examination items. Use standardized examination instructions.</SourceLimits></div>
      <div className="field-grid"><Field label="Current BP (mmHg, systolic/diastolic)" value={n.presentingBP} placeholder="e.g. 160/90" onChange={v => note('presentingBP', v)} /><NumberField label="Glucose (mg/dL)" value={n.glucose} min="1" onChange={v => note('glucose', v)} /><Field id="input-ct-review" label="CT hemorrhage review" value={n.ctHemorrhageStatus} options={[[ '', 'Not reviewed' ], ['absent', 'Hemorrhage absent (reviewed)'], ['present', 'Hemorrhage present (reviewed)'], ['uncertain', 'Uncertain / conflicting']]} onChange={v => note('ctHemorrhageStatus', v)} /></div>
      {acuteIschemic && <><Truth label="Disabling residual deficit" value={n.disablingDeficit} onChange={v => note('disablingDeficit', v)} /><div className="field-grid"><NumberField id="calc-aspects" label="Reviewed ASPECTS (0–10)" value={s.aspects} step="1" min="0" max="10" onChange={v => update(prev => setEncounterReviewedScore(prev, 'aspects', v))} /><NumberField id="calc-pc-aspects" label="Reviewed pc-ASPECTS (0–10)" value={s.pcAspects} step="1" min="0" max="10" onChange={v => update(prev => setEncounterReviewedScore(prev, 'pcAspects', v))} /><Field label="Vessel imaging / segment" value={n.vesselOcclusion[0] || ''} options={[[ '', 'Not documented' ], ...['None', 'ICA', 'M1', 'M2', 'Basilar', 'Other'].map(v => [v, v])]} onChange={v => note('vesselOcclusion', v ? [v] : [])} /></div><p className="workspace-help">A score alone is not a universal EVT gate. Basilar, distal-vessel, large-core and baseline-disability assessments have separate limits.</p><details><summary>Perfusion / MRI selection details</summary><div className="field-grid"><Truth label="MRI pathway selected (No = CTP / EXTEND)" value={n.wakeUpStrokeWorkflow.mriAvailable} onChange={v => nested('mriAvailable', v)} /><NumberField label="Ischemic core (mL)" value={n.coreVolume} min="0" onChange={v => note('coreVolume', v)} /><NumberField label="Total hypoperfused volume (mL, including core)" value={n.penumbraVolume} min="0" onChange={v => note('penumbraVolume', v)} /><Truth label="DWI positive lesion" value={n.wakeUpStrokeWorkflow.dwi?.positiveForLesion} onChange={v => nested('dwi', { positiveForLesion: v })} /><Truth label="FLAIR without marked hyperintensity" value={n.wakeUpStrokeWorkflow.flair?.noMarkedHyperintensity} onChange={v => nested('flair', { noMarkedHyperintensity: v })} /><Truth label="MRI lesion extent reviewed" value={n.wakeUpStrokeWorkflow.mriLesionExtentReviewed} onChange={v => nested('mriLesionExtentReviewed', v)} /><Truth label="Significant mass effect" value={s.evtMassEffect} onChange={v => update({ ...s, evtMassEffect: v })} /></div></details></>}
      <details id="calc-gcs" className="tool-target" open={['ich', 'sah', 'cvt'].includes(n.diagnosisCategory) || undefined}><summary>GCS</summary><div className="field-grid">{[['eye', 'Eye', 4], ['verbal', 'Verbal', 5], ['motor', 'Motor', 6]].map(([key, label, max]) => <Field key={key} label={`GCS ${label}`} value={s.gcs[key] || ''} options={[[ '', 'Not assessed' ], ['UN', 'Not testable'], ...Array.from({ length: max }, (_, i) => [String(i+1), String(i+1)])]} onChange={v => group('gcs', key, v)} />)}</div><Result>{gcs === null ? 'No total: incomplete / not testable' : `GCS ${gcs}/15`}</Result></details>
      {n.diagnosisCategory === 'ich' && <><div id="calc-ich-volume" className="tool-target" tabIndex={-1}><h3>ICH volume · ABC/2</h3><div className="field-grid">{[['a', 'A: largest diameter (cm)'], ['b', 'B: perpendicular diameter (cm)'], ['thicknessMm', 'Slice thickness (mm)'], ['numSlices', 'Number of hematoma slices']].map(([key, label]) => <NumberField key={key} label={label} value={s.volume[key]} min="0" onChange={v => group('volume', key, v)} />)}</div><Result>{volume ? `${volume.volume} mL${volume.unitWarning ? ` · ${volume.unitWarning}` : ''}` : 'Enter three valid positive dimensions in centimeters.'}</Result><SourceLimits url="https://pubmed.ncbi.nlm.nih.gov/8711791/" label="Kothari et al. · ABC/2">Approximate ellipsoid volume, not automated segmentation. Confirm dimensions and units.</SourceLimits></div><div id="calc-ich-score" tabIndex={-1} className="tool-target"><h3>ICH severity score</h3><div className="field-grid"><Truth label="Intraventricular hemorrhage" value={s.ich.ivh} onChange={v => group('ich', 'ivh', v)} /><Truth label="Infratentorial origin" value={s.ich.infratentorial} onChange={v => group('ich', 'infratentorial', v)} /></div><Result>{ich === null ? 'Complete age, GCS, volume and both imaging criteria before scoring.' : `ICH score ${ich}/6 · severity framework; no individual prognosis`}</Result><SourceLimits claim="prognostic-score-limits" /></div></>}
      <details><summary>Examination, imaging & lab details for documentation</summary><div className="field-grid"><TextField label="NIHSS examination details" value={n.nihssDetails} onChange={v => note('nihssDetails', v)} /><Field label="Head CT date (local)" type="date" value={n.ctDate} onChange={v => note('ctDate', v)} /><Field label="Head CT time (local)" type="time" value={n.ctTime} onChange={v => note('ctTime', v)} /><TextField label="Head CT findings" value={n.ctResults} onChange={v => note('ctResults', v)} /><Field label="CTA date (local)" type="date" value={n.ctaDate} onChange={v => note('ctaDate', v)} /><Field label="CTA time (local)" type="time" value={n.ctaTime} onChange={v => note('ctaTime', v)} /><TextField label="CTA head / neck findings" value={n.ctaResults} onChange={v => note('ctaResults', v)} /><TextField label="CT perfusion findings" value={n.ctpResults} onChange={v => note('ctpResults', v)} /><TextField label="Telemetry / EKG findings" value={n.ekgResults} onChange={v => note('ekgResults', v)} /><NumberField label="Heart rate (beats/min)" value={n.heartRate} min="0" onChange={v => note('heartRate', v)} /><NumberField label="SpO₂ (%)" value={n.spO2} min="0" max="100" onChange={v => note('spO2', v)} /><NumberField label="Temperature (°F)" value={n.temperature} onChange={v => note('temperature', v)} /><NumberField label="Platelets (K/µL)" value={n.plateletCount} min="0" onChange={v => note('plateletCount', v)} /><NumberField label="PT (seconds)" value={n.pt} min="0" onChange={v => note('pt', v)} />{!(acuteIschemic && n.lastDOACType === 'warfarin') && <NumberField label="INR" value={n.inr} min="0" onChange={v => note('inr', v)} />}{!(acuteIschemic && n.lastDOACType === 'heparin') && <NumberField label="aPTT (seconds)" value={n.ptt} min="1" onChange={v => note('ptt', v)} />}</div></details>
      <EncounterDetails section="exam" state={s} update={update} />
      <TextField label="Entered examination / imaging assessment" value={s.assessment} onChange={v => update({ ...s, assessment: v })} />
    </Section>
    <Section step="3" id="safety" title="Safety assessment & decision review">
      {acuteIschemic ? <>
        <div className="field-grid"><Field label="Anticoagulant exposure" value={n.lastDOACType} options={[[ '', 'Not assessed' ], ['none', 'None explicitly documented'], ...['apixaban', 'rivaroxaban', 'dabigatran', 'edoxaban', 'warfarin', 'heparin', 'lmwh', 'other'].map(v => [v, v])]} onChange={v => note('lastDOACType', v)} />{n.lastDOACType && n.lastDOACType !== 'none' && <Field label="Last anticoagulant dose (local)" type="datetime-local" value={n.lastDOACDose} onChange={v => note('lastDOACDose', v)} />}{n.lastDOACType === 'lmwh' && <Field label="LMWH dose intent" value={n.anticoagulantDoseIntent} options={[[ '', 'Unknown' ], ['therapeutic', 'Therapeutic'], ['prophylactic', 'Prophylactic']]} onChange={v => note('anticoagulantDoseIntent', v)} />}{n.lastDOACType === 'warfarin' && <NumberField label="INR" value={n.inr} min="0" onChange={v => note('inr', v)} />}{n.lastDOACType === 'heparin' && <NumberField label="aPTT (seconds)" value={n.ptt} min="1" onChange={v => note('ptt', v)} />}</div>
        <Result>{exposure.reason}</Result>
        <p className="workspace-help">Drug-specific review includes dose, timing, renal function and assays. Estimated clearance does not establish IVT eligibility.</p>
      </> : <p className="workspace-help">{n.diagnosisCategory ? `${DIAGNOSES[n.diagnosisCategory]} · document the context-specific specialist assessment and plan.` : 'Select a working diagnosis. Unknown is not a negative finding.'} {s.context === 'follow-up' ? 'Acute reperfusion screens and administration timing are inactive in follow-up context.' : 'Use the retained protocols where applicable.'}</p>}
      <div id="calc-crcl" className="tool-target" tabIndex={-1}><details><summary>Renal calculation · shared age and weight</summary><div className="field-grid"><NumberField label="Creatinine (mg/dL)" value={n.creatinine} min="0.1" onChange={v => note('creatinine', v)} /><NumberField label="Height (cm, optional weight-convention review)" value={n.heightCm} min="0" onChange={v => note('heightCm', v)} /></div><Result>{renal ? `Cockcroft–Gault ${renal.value} mL/min${renal.adjBwValue !== null ? ` · adjusted weight ${renal.adjBwValue} mL/min` : ''}` : 'No result: valid adult age, kg weight, sex coefficient and mg/dL creatinine required.'}</Result>{renal && <p className="workspace-help">{renal.scopeNote}</p>}<SourceLimits url="https://pubmed.ncbi.nlm.nih.gov/1244564/" label="Cockcroft & Gault">Adult estimate; stable creatinine and an appropriate weight convention required. Not a dialysis indication or a stand-alone drug-selection rule.</SourceLimits></details></div>
      {acuteIschemic && <>
        <Result>Safety review: {safetyMissing.length} unanswered items{concerns.length ? ` · ${concerns.length} concerns require review: ${concerns.map(c => c.label).join('; ')}` : ''}</Result>
        <details><summary>Review drug-specific contraindications & concerns</summary><p className="workspace-help">These existing prompts include absolute, relative, correctable and cautionary factors. They require full source and clinician adjudication; an acknowledgement never clears a concern.</p><div className="field-grid">{SAFETY_ITEMS.map(item => <div key={item.id}><Truth label={item.label} value={n.tnkContraindicationChecklist[item.id]} onChange={v => note('tnkContraindicationChecklist', { ...n.tnkContraindicationChecklist, [item.id]: v })} />{item.note && <p className="workspace-help">{item.note}</p>}</div>)}</div></details>
        <label className="workspace-check"><input type="checkbox" checked={n.ivtContraindicationsReviewed} onChange={e => note('ivtContraindicationsReviewed', e.target.checked)} /> Clinician safety review recorded (concerns remain visible)</label>
        <h3>Partial source screens</h3><Result>IVT: {screen.tnk.reason}</Result><Result>EVT: {screen.evt.reason}</Result><SourceLimits url="https://doi.org/10.1161/STR.0000000000000513" label="AHA/ASA AIS 2026">Existing partial adult source screens; not a complete eligibility determination. Review correction notices and full source-specific exclusions. Unknown onset, pediatric cases, disability, large core and posterior circulation require their applicable expert assessment.</SourceLimits>
        {n.lkwUnknown && <Result>Imaging-selected IVT: {n.wakeUpStrokeWorkflow.mriAvailable === true && wake.autoWakeUp || n.wakeUpStrokeWorkflow.mriAvailable === false && wake.autoExtend ? 'Partial source screen met; confirm complete pathway, drug and EVT plan.' : 'Incomplete or outside modeled MRI/perfusion screen.'}</Result>}
        <details id="calc-dawn" className="tool-target"><summary>Historical DAWN / DEFUSE-3 & large-core screens</summary><p className="workspace-help">Limited historical source screens. Failure does not exclude EVT under newer evidence.</p><div id="calc-defuse3">{[['DAWN', evaluateDAWN({ age: n.age, nihss: exam.total, coreMl: n.coreVolume, timeFromLKWh: timing.hours })], ['DEFUSE-3', evaluateDEFUSE3({ age: n.age, nihss: exam.total, coreMl: n.coreVolume, hypoperfusedMl: n.penumbraVolume, timeFromLKWh: timing.hours })]].map(([label, result]) => <Result key={label}>{label}: {result?.reason || 'Required inputs incomplete.'}</Result>)}</div><Result>Large core: {evaluateLargeCoreEVT({ age: n.age, nihss: exam.total, aspects: s.aspects, coreMl: n.coreVolume, timeFromLKWh: timing.hours, premorbidMRS: n.premorbidMRS, lvoLocation: n.vesselOcclusion[0] }).rationale} Mass effect: {typeof s.evtMassEffect === 'boolean' ? s.evtMassEffect ? 'present; specialist review' : 'absent (recorded)' : 'not reviewed'}.</Result><SourceLimits url="https://doi.org/10.1056/NEJMoa1706442" label="DAWN primary publication">Original population and full criteria required; the modeled age/severity/core subset does not determine current EVT eligibility.</SourceLimits><SourceLimits url="https://doi.org/10.1056/NEJMoa1713973" label="DEFUSE-3 primary publication">Hypoperfused volume includes core; trial screening is distinct from a current treatment decision.</SourceLimits></details>
        <div className="field-grid">{['ivt', 'evt'].map(type => <Field key={type} label={`${type.toUpperCase()} clinician decision`} value={s.decisions[type]} options={[[ '', 'Not documented' ], ['Recommended', 'Recommended'], ['Not recommended', 'Not recommended'], ['Specialist review', 'Specialist review / unresolved']]} onChange={v => group('decisions', type, v)} />)}</div>
        <div id="calc-tnk" className="tool-target" tabIndex={-1}><h3>Dose calculation</h3><div className="field-grid"><Field label="Selected IV thrombolytic" value={s.drug} options={[[ '', 'Not selected' ], ['TNK', 'Tenecteplase (TNK)'], ['Alteplase', 'Alteplase']]} onChange={v => update({ ...s, drug: v })} />{s.drug === 'TNK' && <Field label="TNK dose authority" value={s.doseAuthority} options={[[ 'guideline', 'AHA/ASA guideline arithmetic' ], ['fda-label', 'US TNKase label weight bands']]} onChange={v => update({ ...s, doseAuthority: v })} />}</div><div id="calc-alteplase"><Result>{!dose ? 'Select a drug and enter valid weight in kg (greater than 0, at most 350).' : s.drug === 'TNK' ? `TNK ${dose.calculatedDose} mg · ${dose.volume} at labeled 5 mg/mL · ${dose.authorityLabel}` : `Alteplase ${dose.totalDose} mg total · ${dose.bolus} mg bolus over 1 min · ${dose.infusion} mg remaining over 60 min`}</Result></div>{dose && <p className="workspace-help">{dose.roundingNote}</p>}<SourceLimits claim={s.drug === 'Alteplase' ? 'alteplase-stroke-dose' : 'tnk-stroke-dose'} />{s.drug === 'TNK' && <SourceLimits url="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e647640d-c395-4b4b-a0be-1162f9c21d84" label="US TNKase AIS label">The weight-band dose and labeled time window differ from guideline arithmetic and scope. A dose result does not establish eligibility or administration.</SourceLimits>}</div>
      </>}
      {dapt && <details id="calc-dapt" className="tool-target"><summary>Acute DAPT source screen</summary><p className="workspace-help">Treatment-selection logic requires mechanism, hemorrhage exclusion, reperfusion decisions and safety review; it is not arithmetic.</p><Truth label="No reperfusion treatment after review" value={s.dapt.reperfusionExcluded} onChange={v => group('dapt', 'reperfusionExcluded', v)} /><p className="workspace-help">Review this prerequisite in the current diagnosis/context. Changing either makes this review unresolved again; a prior decision does not document absence of treatment.</p>{reperfusionReview.recordedTreatment && <Result>Recorded reperfusion administration or procedure timing conflicts with this exclusion. Reconcile the existing treatment entries before interpreting this screen.</Result>}{daptConcern && <Result>Recorded bleeding concerns remain: {SAFETY_ITEMS.filter(item => ['currentICH', 'activeInternalBleeding', 'lowPlatelets', 'knownBleedingDiathesis', 'recentGIGUBleeding'].includes(item.id) && n.tnkContraindicationChecklist[item.id] === true).map(item => item.label).join('; ')}. An acknowledgement does not clear them.</Result>}<div className="field-grid">{n.diagnosisCategory === 'tia' && <NumberField label="Reviewed ABCD² (0–7)" value={s.dapt.abcd2 ?? ''} min="0" max="7" step="1" onChange={v => update(prev => setEncounterReviewedScore(prev, 'abcd2', v))} />}{[['noncardioembolicConfirmed', 'Noncardioembolic mechanism confirmed'], ['antiplateletContraindicationsReviewed', 'Antiplatelet contraindications reviewed'], ['atherosclerotic', 'Presumed atherosclerotic mechanism'], ['lvdSymptomatic', 'Symptomatic stenosis ≥50%'], ['cyp2c19LOF', 'Known CYP2C19 loss-of-function carrier']].map(([key, label]) => <Truth key={key} label={label} value={s.dapt[key]} onChange={v => group('dapt', key, v)} />)}<Field label="Hemorrhagic risk assessment" value={s.dapt.ichRisk || ''} options={[[ '', 'Not reviewed' ], ['high', 'High / individualized review'], ['reviewed', 'Reviewed; no high-risk finding recorded']]} onChange={v => group('dapt', 'ichRisk', v)} /></div><Result>{s.dapt.ichRisk && ['atherosclerotic', 'lvdSymptomatic', 'cyp2c19LOF'].every(k => typeof s.dapt[k] === 'boolean') ? `${dapt.regimen}: ${dapt.rationale}${dapt.duration ? ` Duration: ${dapt.duration}.` : ''}` : 'Complete the explicit mechanism, risk and genotype review; unknown is not negative.'}</Result><SourceLimits url="https://doi.org/10.1161/STR.0000000000000375" label="AHA/ASA secondary prevention 2021">Modeled CHANCE/POINT/THALES/CHANCE-2/INSPIRES populations have different windows, exclusions and regimens; confirm the complete applicable source. {dapt.source}</SourceLimits></details>}
      <EncounterDetails section="safety" state={s} update={update} /><TiaReadiness state={s} />
      <TextField label="Manual rationale / recommendations" value={s.rationale} onChange={v => update({ ...s, rationale: v })} />
    </Section>
    <Section step="4" id="handoff" title="Documented actions, monitoring & handoff">
      {acuteIschemic && <><div className="field-grid"><Field label="IVT discussion record" value={s.actions.discussion} options={[[ '', 'Not documented' ], ['Discussed', 'Discussed (explicitly recorded)'], ['Not discussed', 'Not discussed (explicitly recorded)']]} onChange={v => group('actions', 'discussion', v)} /><Field label="IVT consent status" value={s.actions.consent} options={[[ '', 'Not documented' ], ['Informed consent', 'Informed consent recorded'], ['Surrogate consent', 'Surrogate consent recorded'], ['Presumed basis', 'Presumed basis recorded'], ['Declined', 'Declined']]} onChange={v => group('actions', 'consent', v)} /><Field label="IVT consent record time (local)" type="datetime-local" value={s.actions.consentTime} onChange={v => group('actions', 'consentTime', v)} /></div><label className="workspace-check"><input type="checkbox" checked={s.actions.administered} onChange={e => group('actions', 'administered', e.target.checked)} /> IV thrombolytic administration explicitly recorded</label><div className="field-grid"><TimestampField label="IVT administration timestamp (local)" shortcut="IVT timestamp" value={s.actions.administrationTime} onChange={v => group('actions', 'administrationTime', v)} /><TimestampField label="EVT puncture timestamp (local)" shortcut="EVT puncture" value={s.actions.punctureTime} onChange={v => group('actions', 'punctureTime', v)} /><TimestampField label="EVT reperfusion timestamp (local)" shortcut="EVT reperfusion" value={s.actions.reperfusionTime} onChange={v => group('actions', 'reperfusionTime', v)} /></div><Result>{schedule ? nextCheck ? `Recorded ${s.drug} administration · next scheduled check ${nextCheck.at.toLocaleTimeString()} (${nextCheck.label})` : '24-hour schedule completed by elapsed time; checks themselves are not attested.' : 'Monitoring timer inactive: explicit administration, drug and a valid past timestamp required.'}</Result><p className="workspace-help">Browser timing cannot guarantee background alarms or clinical monitoring. q15 min ×2 h, q30 min ×6 h, then hourly ×16 h is a schedule aid; attendance is not inferred.</p></>}
      {acuteIschemic && <details><summary>EVT discussion & consent record</summary><div className="field-grid"><Field label="EVT discussion record" value={s.actions.evtDiscussion || ''} options={[[ '', 'Not documented' ], ['Discussed', 'Discussed'], ['Not discussed', 'Not discussed']]} onChange={v => group('actions', 'evtDiscussion', v)} /><Field label="EVT consent status" value={s.actions.evtConsent || ''} options={[[ '', 'Not documented' ], ['Informed consent', 'Informed consent recorded'], ['Surrogate consent', 'Surrogate consent recorded'], ['Presumed basis', 'Presumed basis recorded'], ['Declined', 'Declined']]} onChange={v => group('actions', 'evtConsent', v)} /><Field label="EVT consent record time (local)" type="datetime-local" value={s.actions.evtConsentTime || ''} onChange={v => group('actions', 'evtConsentTime', v)} /></div></details>}
      <details className="documentation-prompts"><summary>Documentation prompts</summary><p className="workspace-help">Insert a prompt into its editable field, then replace the blanks with the documented details.</p><div className="documentation-prompt-actions">{DOCUMENTATION_PROMPTS.filter(prompt => acuteIschemic || prompt.target !== 'discussionDetails').map(prompt => <button key={prompt.id} type="button" className="workspace-secondary-action" onClick={() => { group('actions', prompt.target, appendDocumentationPrompt(s.actions[prompt.target], prompt.text)); focusEncounterTarget(`action-${prompt.target}`); }}>{prompt.label}</button>)}</div></details>
      <TextField id="action-discussionDetails" label="Discussion details" value={s.actions.discussionDetails} onChange={v => group('actions', 'discussionDetails', v)} />
      <TextField id="action-monitoring" label="Monitoring actions explicitly documented" value={s.actions.monitoring} onChange={v => group('actions', 'monitoring', v)} /><div className="field-grid"><Field id="input-disposition" label="Disposition" value={s.actions.disposition} options={[[ '', 'Not documented' ], ['Transfer', 'Transfer'], ['Admission', 'Admission'], ['Discharge', 'Discharge'], ['Follow-up', 'Follow-up'], ['Pending', 'Pending']]} onChange={v => group('actions', 'disposition', v)} /><TextField id="action-handoff" label="Handoff record" value={s.actions.handoff} onChange={v => group('actions', 'handoff', v)} /></div>
      <nav className="reference-links" aria-label="Related clinical evidence"><a href={`#/evidence/${({ischemic: s.context === 'acute' ? 'acute-reperfusion' : 'secondary-prevention', tia: 'tia-evaluation', ich: 'ich-management', sah: 'sah', cvt: 'cvt'})[n.diagnosisCategory] || 'stroke-workup'}`}>Related clinical guidance</a><a href="#/evidence/stroke-workup">Etiology & workup</a><a href="#/evidence/af-timing">Anticoagulation timing</a>{s.context === 'follow-up' && <a href="#/evidence/recovery">Recovery & participation</a>}</nav>
      <EncounterDetails section="handoff" state={s} update={update} />
      {acuteIschemic && <Field label="Recorded mTICI grade" value={n.ticiScore || ''} options={[[ '', 'Not recorded' ], ...['0', '1', '2a', '2b', '2c', '3'].map(value => [value, `${value}: ${MTICI_DESCRIPTORS[value]}`])]} onChange={value => note('ticiScore', value)} />}
      <Field label="Documentation format" value={s.documentFormat || 'consultation'} options={DOCUMENT_FORMATS} onChange={value => update(prev => ({ ...prev, documentFormat: value }))} />
      <h3>{documentLabel}</h3>
      {warning.length > 0 && <p role="alert">Copy and generation blocked: {warning.join('; ')}. Review the flagged entries before generating or copying.</p>}
      <button type="button" className="workspace-primary" disabled={warning.length > 0} onClick={() => onGenerate(buildSummary(s, Date.now()))}>{`Generate ${documentLabel}`}</button>
      {s.draft && (s.draft.stale ? <p role="status">Encounter inputs changed. Generate again before reviewing or copying.</p> : <div className="generated-summary"><textarea data-generated-note aria-label={`Generated ${documentLabel}`} readOnly value={s.draft.text} rows={12} /><button type="button" className="workspace-primary" onClick={() => onCopy(s.draft.text)}>{`Copy ${documentLabel}`}</button><p role="status">{copyStatus}</p></div>)}
    </Section>
  </div>;
}
