// src/evidence/completedTrials.js
//
// Completed / landmark trials. The Atlas's "what does the literature say"
// surface. NEVER used as eligibility criteria — those live in activeTrials.js.
//
// Seed data is drawn from docs/evidence-review-2021-2026.md (PMID-verified)
// and from existing inline references in src/app.jsx Management content.
// Where a precise numeric (effectSize, CI, pValue) was not available locally,
// the field is left as a short qualitative summary and verificationNotes flag
// the limitation. No live network lookups were performed.

import { makeCompletedTrial } from './schema.js';

const lr = '2026-04-25';

// Helper to keep records compact while still type-safe.
const t = makeCompletedTrial;

export const completedTrials = [
  // ------------------- Tenecteplase vs alteplase -------------------
  t({
    id: 'act',
    shortName: 'AcT',
    fullName: 'Intravenous Tenecteplase Compared with Alteplase for Acute Ischaemic Stroke in Canada',
    topic: 'tnk-vs-alteplase',
    diseaseArea: ['acute-ischemic-stroke', 'tnk-vs-alteplase'],
    population: {
      n: 1577,
      ageRange: 'adults ≥18',
      nihssRange: 'all eligible',
      timeWindow: '≤4.5 h',
      keyInclusion: ['IVT-eligible AIS within 4.5 h'],
      keyExclusion: ['Standard alteplase contraindications']
    },
    intervention: 'Tenecteplase 0.25 mg/kg (max 25 mg) IV bolus',
    comparator: 'Alteplase 0.9 mg/kg IV (10% bolus + 60-min infusion)',
    primaryEndpoint: {
      definition: 'mRS 0-1 at 90-120 days',
      timepoint: '90-120 d',
      result: 'Non-inferior: 36.9% (TNK) vs 34.8% (alteplase)',
      effectSize: 'Risk difference 2.1%',
      confidenceInterval: '95% CI -2.6% to 6.9%',
      pValue: 'Non-inferiority margin met'
    },
    secondaryEndpoints: [
      { name: 'Symptomatic ICH', result: 'Similar between groups' },
      { name: '90-day mortality', result: 'Similar' }
    ],
    safetyFindings: { sich: 'Similar to alteplase', mortality: 'Similar', other: '' },
    imagingCriteria: 'Standard CT-based selection',
    applicabilityNotes: 'Pragmatic, non-inferior — supports TNK as first-line in eligible AIS, especially when EVT is anticipated.',
    limitations: 'Open-label; primary endpoint included mRS 0-1 only.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-act-2022'],
    relatedActiveTrialIds: ['most'],
    practiceImpact: 'Supports TNK 0.25 mg/kg as a preferred IV thrombolytic for IVT-eligible AIS within 4.5 h.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'trace-2',
    shortName: 'TRACE-2',
    fullName: 'Trial of Tenecteplase in Chinese Patients with Acute Ischemic Stroke',
    topic: 'tnk-vs-alteplase',
    diseaseArea: ['acute-ischemic-stroke', 'tnk-vs-alteplase'],
    population: { n: 1430, ageRange: '≥18', nihssRange: 'NIHSS not >25', timeWindow: '≤4.5 h', keyInclusion: ['IVT-eligible'], keyExclusion: ['EVT-intended in some sites'] },
    intervention: 'Tenecteplase 0.25 mg/kg',
    comparator: 'Alteplase 0.9 mg/kg',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Non-inferior: 62.0% (TNK) vs 58.0% (alteplase)', effectSize: 'RR 1.07', confidenceInterval: '95% CI 0.98 to 1.16', pValue: 'Non-inferiority met' },
    secondaryEndpoints: [{ name: 'sICH', result: 'Similar' }],
    safetyFindings: { sich: '~2% in both groups', mortality: 'Similar', other: '' },
    imagingCriteria: 'NIHSS-driven, NCCT',
    applicabilityNotes: 'External validity in East Asian population.',
    limitations: 'Excluded LVO with intended EVT in many sites.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-trace2-2023'],
    relatedActiveTrialIds: ['most'],
    practiceImpact: 'Confirms non-inferiority of TNK in non-LVO eligible AIS within 4.5 h.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'original',
    shortName: 'ORIGINAL',
    fullName: 'Tenecteplase vs Alteplase in AIS (ORIGINAL)',
    topic: 'tnk-vs-alteplase',
    diseaseArea: ['acute-ischemic-stroke'],
    population: { n: 1489, ageRange: '≥18', nihssRange: 'all eligible', timeWindow: '≤4.5 h', keyInclusion: ['IVT-eligible AIS within 4.5 h'], keyExclusion: ['Standard contraindications'] },
    intervention: 'TNK 0.25 mg/kg',
    comparator: 'Alteplase 0.9 mg/kg',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Non-inferior', effectSize: 'See publication', confidenceInterval: '', pValue: 'Non-inferiority met' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: '' },
    imagingCriteria: 'NCCT',
    applicabilityNotes: '',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-original-2024'],
    relatedActiveTrialIds: ['most'],
    practiceImpact: 'Adds further RCT support for TNK as alteplase-equivalent first-line.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- Late window IVT -------------------
  t({
    id: 'wake-up',
    shortName: 'WAKE-UP',
    fullName: 'MRI-Guided Thrombolysis for Stroke with Unknown Time of Onset',
    topic: 'wake-up-stroke',
    diseaseArea: ['acute-ischemic-stroke', 'wake-up-stroke', 'extended-window-ivt'],
    population: { n: 503, ageRange: '18-80', nihssRange: 'NIHSS ≤25', timeWindow: 'unknown onset (last seen well >4.5 h)', keyInclusion: ['DWI-FLAIR mismatch on MRI', 'Pre-stroke mRS 0-1'], keyExclusion: ['Planned thrombectomy'] },
    intervention: 'IV alteplase 0.9 mg/kg',
    comparator: 'Placebo / standard care',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Favored alteplase: 53.3% vs 41.8%', effectSize: 'OR 1.61', confidenceInterval: '95% CI 1.09 to 2.36', pValue: 'p=0.02' },
    secondaryEndpoints: [{ name: 'Mortality at 90 d', result: 'Numerically higher with alteplase, not significant' }],
    safetyFindings: { sich: '2.0% (alteplase) vs 0.4% (control)', mortality: '4.1% vs 1.2%', other: 'Trial halted early for funding' },
    imagingCriteria: 'DWI-FLAIR mismatch on MRI',
    applicabilityNotes: 'Applies to MRI-equipped centers; supports MRI-based selection in unknown-onset stroke.',
    limitations: 'Early termination; modest absolute benefit with non-trivial sICH increase.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-wake-up-2018'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Foundational evidence for imaging-selected thrombolysis in wake-up / unknown onset stroke.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'extend',
    shortName: 'EXTEND',
    fullName: 'Thrombolysis Guided by Perfusion Imaging up to 9 Hours after Onset',
    topic: 'extended-window-ivt',
    diseaseArea: ['acute-ischemic-stroke', 'extended-window-ivt'],
    population: { n: 225, ageRange: '≥18', nihssRange: '4-26', timeWindow: '4.5-9 h or wake-up', keyInclusion: ['Perfusion-imaging mismatch (core <70 mL, mismatch ratio >1.2, mismatch volume >10 mL)'], keyExclusion: ['LVO with planned EVT'] },
    intervention: 'IV alteplase 0.9 mg/kg',
    comparator: 'Placebo',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Favored alteplase: 35.4% vs 29.5%', effectSize: 'Adjusted RR 1.44', confidenceInterval: '95% CI 1.01 to 2.06', pValue: 'p=0.04' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '6.2% (alteplase) vs 0.9% (placebo)', mortality: '11.5% vs 8.9%', other: '' },
    imagingCriteria: 'CTP / MR-PWI core-mismatch',
    applicabilityNotes: 'Population had ~70% non-LVO; provides direct evidence for late-window selection in EVT-ineligible.',
    limitations: 'Stopped early after WAKE-UP results; modest sample size.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-extend-2019'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Supports perfusion-mismatch IVT in 4.5-9 h window when EVT not indicated.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'epithet',
    shortName: 'EPITHET',
    fullName: 'Echoplanar Imaging Thrombolytic Evaluation Trial',
    topic: 'extended-window-ivt',
    diseaseArea: ['acute-ischemic-stroke'],
    population: { n: 101, ageRange: '≥18', nihssRange: '4-22', timeWindow: '3-6 h', keyInclusion: ['MR-PWI/DWI mismatch'], keyExclusion: [] },
    intervention: 'IV alteplase',
    comparator: 'Placebo',
    primaryEndpoint: { definition: 'Infarct growth at 90 d', timepoint: '90 d', result: 'Reduced infarct growth in mismatch group; clinical co-primary not significant', effectSize: '', confidenceInterval: '', pValue: '' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '', mortality: '', other: '' },
    imagingCriteria: 'PWI/DWI mismatch',
    applicabilityNotes: 'Hypothesis-generating for mismatch-based selection.',
    limitations: 'Small; surrogate endpoint primary.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-epithet-2008'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Conceptual basis for later mismatch-based late-window trials.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'ecass4-extend',
    shortName: 'ECASS4-EXTEND',
    fullName: 'Extending the Time Window for IV Thrombolysis Using MRI-based Selection',
    topic: 'extended-window-ivt',
    diseaseArea: ['acute-ischemic-stroke'],
    population: { n: 119, ageRange: '18-85', nihssRange: '≥4', timeWindow: '4.5-9 h', keyInclusion: ['MRI mismatch'], keyExclusion: [] },
    intervention: 'IV alteplase',
    comparator: 'Placebo',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Favored alteplase numerically; not statistically significant after early termination', effectSize: '', confidenceInterval: '', pValue: '' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '', mortality: '', other: '' },
    imagingCriteria: 'MRI mismatch',
    applicabilityNotes: 'Trial stopped early after WAKE-UP / EXTEND results.',
    limitations: 'Underpowered after early stop.',
    certainty: 'low',
    evidenceType: 'rct',
    citationIds: ['cit-ecass4-2018'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Adds to the late-window mismatch evidence base; not independently practice-changing.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'timeless',
    shortName: 'TIMELESS',
    fullName: 'Tenecteplase for Stroke at 4.5 to 24 Hours with Perfusion-Imaging Selection',
    topic: 'extended-window-ivt',
    diseaseArea: ['acute-ischemic-stroke', 'extended-window-ivt', 'tnk-vs-alteplase'],
    population: { n: 458, ageRange: '≥18', nihssRange: '≥5', timeWindow: '4.5-24 h', keyInclusion: ['Anterior LVO + salvageable tissue (CTP mismatch)'], keyExclusion: [] },
    intervention: 'TNK 0.25 mg/kg IV',
    comparator: 'Placebo',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored TNK numerically; primary endpoint did not reach significance overall', effectSize: 'Adjusted common OR ~1.13', confidenceInterval: '95% CI ~0.82 to 1.57', pValue: 'p=0.45 (overall)' },
    secondaryEndpoints: [{ name: 'Pre-EVT reperfusion', result: 'Higher with TNK' }],
    safetyFindings: { sich: '3.2% (TNK) vs 2.3% (placebo)', mortality: 'Similar', other: '' },
    imagingCriteria: 'CTP mismatch, RAPID',
    applicabilityNotes: 'Population had high EVT use; benefit may have been masked.',
    limitations: 'Statistically non-significant primary; subgroup signals only.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-timeless-2024'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Cautionary: late-window TNK alone (with EVT permitted) did not meet its primary endpoint.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'twist',
    shortName: 'TWIST',
    fullName: 'Tenecteplase in Wake-up Ischaemic Stroke Trial',
    topic: 'wake-up-stroke',
    diseaseArea: ['acute-ischemic-stroke', 'wake-up-stroke'],
    population: { n: 578, ageRange: '≥18', nihssRange: 'all eligible', timeWindow: 'wake-up <4.5 h after waking', keyInclusion: ['Wake-up AIS, NCCT-only selection'], keyExclusion: [] },
    intervention: 'TNK 0.25 mg/kg',
    comparator: 'Standard care',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'No significant benefit overall', effectSize: '', confidenceInterval: '', pValue: 'p ns' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: '' },
    imagingCriteria: 'NCCT only (no advanced imaging)',
    applicabilityNotes: 'Negative for unselected wake-up TNK; reinforces need for imaging-based selection.',
    limitations: 'Open-label; no advanced imaging.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-twist-2023'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Late-window thrombolysis without advanced imaging is not supported.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'trace-iii',
    shortName: 'TRACE-III',
    fullName: 'Tenecteplase for Ischemic Stroke 4.5-24 Hours without Thrombectomy',
    topic: 'extended-window-ivt',
    diseaseArea: ['acute-ischemic-stroke', 'extended-window-ivt'],
    population: { n: 516, ageRange: '≥18', nihssRange: '≥6', timeWindow: '4.5-24 h', keyInclusion: ['LVO without planned EVT', 'Salvageable tissue (perfusion mismatch)'], keyExclusion: ['EVT planned or available'] },
    intervention: 'TNK 0.25 mg/kg',
    comparator: 'Standard care',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Favored TNK: 33.0% vs 24.2%', effectSize: 'RR 1.37', confidenceInterval: '95% CI 1.04 to 1.81', pValue: 'p=0.03' },
    secondaryEndpoints: [{ name: 'sICH', result: '3.0% (TNK) vs 0.8% (control)' }],
    safetyFindings: { sich: '3.0% vs 0.8%', mortality: 'Similar', other: '' },
    imagingCriteria: 'CTP mismatch / penumbra',
    applicabilityNotes: 'Pure EVT-ineligible population — directly supports the SISTER niche.',
    limitations: 'Single-region (China); needs replication.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-trace-iii-2024'],
    relatedActiveTrialIds: ['sister'],
    practiceImpact: 'Strongest evidence to date for late-window TNK in EVT-ineligible LVO.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- EVT large-core / late window -------------------
  t({
    id: 'select2',
    shortName: 'SELECT2',
    fullName: 'Trial of Endovascular Thrombectomy for Large Ischemic Strokes',
    topic: 'evt-large-core',
    diseaseArea: ['acute-ischemic-stroke', 'evt-large-core'],
    population: { n: 352, ageRange: '18-85', nihssRange: '≥6', timeWindow: '≤24 h', keyInclusion: ['ASPECTS 3-5 or core 50-100 mL'], keyExclusion: [] },
    intervention: 'EVT plus medical therapy',
    comparator: 'Medical therapy alone',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored EVT (generalized OR 1.51)', effectSize: 'OR 1.51', confidenceInterval: '95% CI 1.20 to 1.89', pValue: 'p<0.001' },
    secondaryEndpoints: [{ name: 'mRS 0-3', result: 'Higher with EVT' }],
    safetyFindings: { sich: '0.6% (EVT) vs 1.1% (control)', mortality: 'Similar', other: 'Vascular complications more frequent with EVT' },
    imagingCriteria: 'CT or MRI; ASPECTS 3-5 or core 50-100 mL',
    applicabilityNotes: 'Establishes EVT benefit for large-core anterior-circulation LVO up to 24 h.',
    limitations: 'Open-label; modest absolute benefit at lower ASPECTS.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-select2-2023'],
    relatedActiveTrialIds: ['tested'],
    practiceImpact: 'Supports EVT for large-core; large core is no longer an automatic exclusion.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'angel-aspect',
    shortName: 'ANGEL-ASPECT',
    fullName: 'Endovascular Therapy for Acute Ischemic Stroke with Large Infarct',
    topic: 'evt-large-core',
    diseaseArea: ['acute-ischemic-stroke', 'evt-large-core'],
    population: { n: 456, ageRange: '18-80', nihssRange: '6-30', timeWindow: '≤24 h', keyInclusion: ['ASPECTS 3-5 or core 70-100 mL'], keyExclusion: [] },
    intervention: 'EVT + medical management',
    comparator: 'Medical management',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored EVT', effectSize: 'OR 1.37', confidenceInterval: '95% CI 1.11 to 1.69', pValue: 'p=0.004' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '6.1% vs 2.7%', mortality: 'Similar', other: '' },
    imagingCriteria: 'ASPECTS 3-5 or core 70-100 mL',
    applicabilityNotes: 'Chinese population; complementary to SELECT2.',
    limitations: 'Open-label.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-angel-aspect-2023'],
    relatedActiveTrialIds: ['tested'],
    practiceImpact: 'Confirms EVT benefit in large-core population.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'rescue-japan-limit',
    shortName: 'RESCUE-Japan LIMIT',
    fullName: 'Endovascular Therapy for Acute Stroke with Large Ischemic Region',
    topic: 'evt-large-core',
    diseaseArea: ['acute-ischemic-stroke', 'evt-large-core'],
    population: { n: 203, ageRange: '≥18', nihssRange: '6-30', timeWindow: '≤24 h', keyInclusion: ['ASPECTS 3-5 on CT'], keyExclusion: [] },
    intervention: 'EVT + medical care',
    comparator: 'Medical care',
    primaryEndpoint: { definition: 'mRS 0-3 at 90 d', timepoint: '90 d', result: '31.0% (EVT) vs 12.7% (control)', effectSize: 'RR 2.43', confidenceInterval: '95% CI 1.35 to 4.37', pValue: 'p=0.002' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '9% vs 4.5%', mortality: 'Similar', other: '' },
    imagingCriteria: 'NCCT ASPECTS 3-5',
    applicabilityNotes: 'Established large-core EVT benefit pre-SELECT2 / ANGEL-ASPECT.',
    limitations: 'Single-country.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-rescue-japan-2022'],
    relatedActiveTrialIds: ['tested'],
    practiceImpact: 'First major RCT to support large-core EVT.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'tension',
    shortName: 'TENSION',
    fullName: 'Endovascular Thrombectomy for AIS with Established Large Infarct',
    topic: 'evt-large-core',
    diseaseArea: ['acute-ischemic-stroke', 'evt-large-core'],
    population: { n: 253, ageRange: '18-85', nihssRange: '≥6', timeWindow: '≤12 h', keyInclusion: ['ASPECTS 3-5'], keyExclusion: [] },
    intervention: 'EVT + medical care',
    comparator: 'Medical care',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored EVT', effectSize: 'Adjusted common OR 2.58', confidenceInterval: '95% CI 1.60 to 4.15', pValue: 'p<0.001' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '5.6% vs 0%', mortality: 'Similar', other: '' },
    imagingCriteria: 'ASPECTS 3-5, ≤12 h',
    applicabilityNotes: '',
    limitations: 'Stopped early for efficacy.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-tension-2023'],
    relatedActiveTrialIds: ['tested'],
    practiceImpact: 'European replication of large-core EVT benefit.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'dawn',
    shortName: 'DAWN',
    fullName: 'Thrombectomy 6 to 24 Hours after Stroke with Mismatch between Deficit and Infarct',
    topic: 'evt-late-window',
    diseaseArea: ['acute-ischemic-stroke', 'evt-late-window'],
    population: { n: 206, ageRange: '≥18', nihssRange: '≥10', timeWindow: '6-24 h', keyInclusion: ['Clinical-core mismatch'], keyExclusion: [] },
    intervention: 'EVT',
    comparator: 'Medical therapy',
    primaryEndpoint: { definition: 'mRS shift / 90-d functional independence', timepoint: '90 d', result: 'Favored EVT: 49% vs 13% (functional independence)', effectSize: 'Adjusted difference 33%', confidenceInterval: '95% CI 21% to 44%', pValue: 'p<0.001' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '6% vs 3%', mortality: 'Similar', other: '' },
    imagingCriteria: 'Clinical-core mismatch (NIHSS-based)',
    applicabilityNotes: 'Established late-window EVT.',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-dawn-2018'],
    relatedActiveTrialIds: ['step-evt'],
    practiceImpact: 'Foundational evidence for late-window EVT.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'defuse-3',
    shortName: 'DEFUSE-3',
    fullName: 'Thrombectomy at 6-16 Hours with Selection by Perfusion Imaging',
    topic: 'evt-late-window',
    diseaseArea: ['acute-ischemic-stroke', 'evt-late-window'],
    population: { n: 182, ageRange: '18-90', nihssRange: '≥6', timeWindow: '6-16 h', keyInclusion: ['Core <70 mL, mismatch ratio >1.8, mismatch volume >15 mL'], keyExclusion: [] },
    intervention: 'EVT',
    comparator: 'Medical therapy',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored EVT', effectSize: 'OR 2.77', confidenceInterval: '95% CI 1.63 to 4.70', pValue: 'p<0.001' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '7% vs 4%', mortality: '14% vs 26%', other: '' },
    imagingCriteria: 'CTP / MR-PWI mismatch',
    applicabilityNotes: '',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-defuse3-2018'],
    relatedActiveTrialIds: ['step-evt'],
    practiceImpact: 'Established perfusion-mismatch criteria for late-window EVT.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- IA adjunct after EVT -------------------
  t({
    id: 'choice',
    shortName: 'CHOICE',
    fullName: 'Intra-arterial Alteplase Following Successful Thrombectomy',
    topic: 'ia-adjunct-after-evt',
    diseaseArea: ['acute-ischemic-stroke'],
    population: { n: 121, ageRange: '≥18', nihssRange: 'all', timeWindow: 'post-EVT', keyInclusion: ['Successful EVT (mTICI 2b/3)'], keyExclusion: [] },
    intervention: 'Intra-arterial alteplase (post-EVT)',
    comparator: 'Placebo',
    primaryEndpoint: { definition: 'mRS 0-1 at 90 d', timepoint: '90 d', result: 'Favored alteplase: 59.0% vs 40.4%', effectSize: 'Adjusted RR 1.59', confidenceInterval: '95% CI 1.07 to 2.36', pValue: 'p=0.047' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'No significant increase', mortality: 'Similar', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Hypothesis-generating; replication ongoing.',
    limitations: 'Small; stopped early.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-choice-2022'],
    relatedActiveTrialIds: [],
    practiceImpact: 'IA alteplase after successful EVT may improve outcomes; not yet standard of care.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- CRAO -------------------
  t({
    id: 'theia',
    shortName: 'THEIA',
    fullName: 'Thrombolysis for Central Retinal Artery Occlusion',
    topic: 'crao-thrombolysis',
    diseaseArea: ['crao-thrombolysis'],
    population: { n: 71, ageRange: '≥18', nihssRange: 'n/a', timeWindow: '≤4.5 h from vision loss', keyInclusion: ['CRAO with visual acuity ≤20/200'], keyExclusion: [] },
    intervention: 'IV alteplase 0.9 mg/kg',
    comparator: 'Standard care',
    primaryEndpoint: { definition: 'Visual acuity improvement', timepoint: '7 d / 30 d', result: 'No significant benefit overall (qualitative summary)', effectSize: '', confidenceInterval: '', pValue: '' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '', mortality: 'No deaths', other: '' },
    imagingCriteria: 'Ophthalmologic exam',
    applicabilityNotes: 'CRAO thrombolysis remains investigational; benefit population-uncertain.',
    limitations: 'Small; underpowered.',
    certainty: 'low',
    evidenceType: 'rct',
    citationIds: ['cit-theia-2023'],
    relatedActiveTrialIds: [],
    practiceImpact: 'CRAO IVT is reasonable in selected centers; no strong RCT support yet.',
    lastReviewed: lr,
    verificationStatus: 'unverified-source-limited',
    verificationNotes: 'Numeric primary-endpoint precision left qualitative pending manual verification.'
  }),

  // ------------------- ICH -------------------
  t({
    id: 'interact3',
    shortName: 'INTERACT3',
    fullName: 'Care Bundle Approach for Acute Intracerebral Haemorrhage',
    topic: 'ich-bp-management',
    diseaseArea: ['ich', 'ich-bp-management'],
    population: { n: 7036, ageRange: '≥18', nihssRange: 'n/a', timeWindow: '<6 h from onset', keyInclusion: ['Acute spontaneous ICH'], keyExclusion: ['Massive ICH with imminent death'] },
    intervention: 'Care bundle (intensive BP lowering to <140 mmHg, glucose 6.1-7.8 mmol/L, temperature <37.5°C, anticoagulant reversal)',
    comparator: 'Usual care',
    primaryEndpoint: { definition: 'mRS shift at 6 mo', timepoint: '6 mo', result: 'Favored bundle', effectSize: 'Adjusted common OR 0.86', confidenceInterval: '95% CI 0.76 to 0.97', pValue: 'p=0.015' },
    secondaryEndpoints: [{ name: 'Mortality at 6 mo', result: 'Favored bundle' }],
    safetyFindings: { sich: 'n/a', mortality: 'Lower with bundle', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Implementation-focused: bundle not single-component.',
    limitations: 'Cluster-randomized; bundle effects cannot be attributed to single component.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-interact3-2023'],
    relatedActiveTrialIds: ['saturn'],
    practiceImpact: 'Establishes care-bundle approach for acute ICH.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'annexa-i',
    shortName: 'ANNEXA-I',
    fullName: 'Andexanet for Factor Xa Inhibitor-Associated Acute ICH',
    topic: 'ich-anticoag-reversal',
    diseaseArea: ['ich', 'ich-anticoag-reversal'],
    population: { n: 530, ageRange: '≥18', nihssRange: 'n/a', timeWindow: '≤15 h from last FXa dose, ≤6 h from ICH onset', keyInclusion: ['ICH on apixaban/rivaroxaban/edoxaban'], keyExclusion: [] },
    intervention: 'Andexanet alfa',
    comparator: 'Usual care (predominantly 4F-PCC)',
    primaryEndpoint: { definition: 'Hemostatic efficacy at 12 h', timepoint: '12 h', result: 'Favored andexanet: 67.0% vs 53.1%', effectSize: 'Adjusted difference 13.4%', confidenceInterval: '95% CI 4.6 to 22.2', pValue: 'p=0.003' },
    secondaryEndpoints: [{ name: 'Thrombotic events at 30 d', result: '10.3% (andexanet) vs 5.6% (usual care)' }],
    safetyFindings: { sich: 'n/a', mortality: 'Similar at 30 d', other: 'More thrombotic events with andexanet' },
    imagingCriteria: '',
    applicabilityNotes: 'Hemostatic benefit comes with thrombotic-risk trade-off.',
    limitations: 'Open-label; usual care heterogeneous.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-annexa-i-2024'],
    relatedActiveTrialIds: [],
    practiceImpact: 'AHA/ASA 2022 lists andexanet as Class IIa for FXa-associated ICH; ANNEXA-I refines hemostatic-vs-thrombotic trade-off.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'enrich',
    shortName: 'ENRICH',
    fullName: 'Early Minimally Invasive Removal of Intracerebral Hemorrhage',
    topic: 'ich-surgery',
    diseaseArea: ['ich', 'ich-surgery'],
    population: { n: 300, ageRange: '18-80', nihssRange: 'n/a', timeWindow: '≤24 h from onset', keyInclusion: ['ICH 30-80 mL, lobar (after early stop in deep cohort)'], keyExclusion: [] },
    intervention: 'Early minimally invasive parafascicular evacuation + standard care',
    comparator: 'Standard medical care',
    primaryEndpoint: { definition: 'Utility-weighted mRS at 180 d', timepoint: '180 d', result: 'Favored surgery (Bayesian posterior probability >0.95)', effectSize: 'Mean difference 0.13', confidenceInterval: '95% CrI 0.04 to 0.22', pValue: '' },
    secondaryEndpoints: [{ name: 'Mortality at 30 d', result: 'No significant difference' }],
    safetyFindings: { sich: 'n/a', mortality: 'Similar', other: '' },
    imagingCriteria: 'CT-confirmed ICH 30-80 mL',
    applicabilityNotes: 'Adaptive design enriched for lobar; deep ICH did not benefit and was stopped.',
    limitations: 'Open-label; specific device.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-enrich-2024'],
    relatedActiveTrialIds: ['saturn'],
    practiceImpact: 'Supports early minimally invasive evacuation for lobar ICH at capable centers.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- DAPT -------------------
  t({
    id: 'chance',
    shortName: 'CHANCE',
    fullName: 'Clopidogrel with Aspirin in Acute Minor Stroke or TIA',
    topic: 'dapt-minor-stroke',
    diseaseArea: ['secondary-prevention', 'dapt-minor-stroke'],
    population: { n: 5170, ageRange: '≥40', nihssRange: 'NIHSS ≤3 (or high-risk TIA)', timeWindow: '≤24 h', keyInclusion: ['Minor stroke or high-risk TIA'], keyExclusion: ['Cardioembolic source'] },
    intervention: 'Aspirin + clopidogrel x 21 days, then clopidogrel x 90 d',
    comparator: 'Aspirin alone x 90 d',
    primaryEndpoint: { definition: 'New stroke at 90 d', timepoint: '90 d', result: 'Favored DAPT: 8.2% vs 11.7%', effectSize: 'HR 0.68', confidenceInterval: '95% CI 0.57 to 0.81', pValue: 'p<0.001' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: 'Bleeding similar' },
    imagingCriteria: '',
    applicabilityNotes: 'Chinese population; ABCD² ≥4 or NIHSS ≤3.',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-chance-2013'],
    relatedActiveTrialIds: ['captiva'],
    practiceImpact: 'Founding evidence for short-course DAPT in minor stroke / high-risk TIA.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'point',
    shortName: 'POINT',
    fullName: 'Clopidogrel and Aspirin in Acute Ischemic Stroke and High-Risk TIA',
    topic: 'dapt-minor-stroke',
    diseaseArea: ['secondary-prevention', 'dapt-minor-stroke'],
    population: { n: 4881, ageRange: '≥18', nihssRange: 'NIHSS ≤3', timeWindow: '≤12 h', keyInclusion: ['Minor stroke or high-risk TIA'], keyExclusion: [] },
    intervention: 'Aspirin + clopidogrel x 90 days',
    comparator: 'Aspirin alone',
    primaryEndpoint: { definition: 'Major ischemic event at 90 d', timepoint: '90 d', result: 'Favored DAPT: 5.0% vs 6.5%', effectSize: 'HR 0.75', confidenceInterval: '95% CI 0.59 to 0.95', pValue: 'p=0.02' },
    secondaryEndpoints: [{ name: 'Major hemorrhage', result: 'Increased with DAPT (0.9% vs 0.4%)' }],
    safetyFindings: { sich: '', mortality: 'Similar', other: 'Bleeding higher with DAPT' },
    imagingCriteria: '',
    applicabilityNotes: 'Bleeding excess emerges after ~21 days, supporting short-course strategy.',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-point-2018'],
    relatedActiveTrialIds: ['captiva'],
    practiceImpact: 'Reinforces 21-day cap on DAPT for minor stroke.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'thales',
    shortName: 'THALES',
    fullName: 'Ticagrelor and Aspirin or Aspirin Alone in AIS or TIA',
    topic: 'dapt-minor-stroke',
    diseaseArea: ['secondary-prevention', 'dapt-minor-stroke'],
    population: { n: 11016, ageRange: '≥40', nihssRange: 'NIHSS ≤5', timeWindow: '≤24 h', keyInclusion: ['Mild/moderate AIS or high-risk TIA'], keyExclusion: ['Cardioembolic'] },
    intervention: 'Ticagrelor + aspirin x 30 d',
    comparator: 'Aspirin alone',
    primaryEndpoint: { definition: 'Stroke or death at 30 d', timepoint: '30 d', result: 'Favored DAPT: 5.5% vs 6.6%', effectSize: 'HR 0.83', confidenceInterval: '95% CI 0.71 to 0.96', pValue: 'p=0.02' },
    secondaryEndpoints: [{ name: 'Severe bleeding', result: '0.5% vs 0.1%' }],
    safetyFindings: { sich: '', mortality: 'Similar', other: 'Severe bleeding higher with DAPT' },
    imagingCriteria: '',
    applicabilityNotes: 'Ticagrelor-based alternative to clopidogrel-based DAPT.',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-thales-2020'],
    relatedActiveTrialIds: ['captiva'],
    practiceImpact: 'Supports ticagrelor-based DAPT, especially when CYP2C19 LOF suspected.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'inspires',
    shortName: 'INSPIRES',
    fullName: 'Dual Antiplatelet Treatment up to 72 Hours after Ischemic Stroke',
    topic: 'dapt-minor-stroke',
    diseaseArea: ['secondary-prevention', 'dapt-minor-stroke'],
    population: { n: 6100, ageRange: '≥35', nihssRange: 'mild stroke or high-risk TIA', timeWindow: '≤72 h', keyInclusion: ['Mild AIS or high-risk TIA, ≤72 h'], keyExclusion: [] },
    intervention: 'Aspirin + clopidogrel x 21 days, started up to 72 h',
    comparator: 'Aspirin alone',
    primaryEndpoint: { definition: 'New stroke at 90 d', timepoint: '90 d', result: 'Favored DAPT', effectSize: 'HR 0.79', confidenceInterval: '95% CI 0.66 to 0.94', pValue: 'p=0.008' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '', mortality: '', other: 'Moderate-to-severe bleeding higher with DAPT' },
    imagingCriteria: '',
    applicabilityNotes: 'Extends DAPT eligibility window from 24 h to 72 h.',
    limitations: '',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-inspires-2024'],
    relatedActiveTrialIds: ['captiva'],
    practiceImpact: 'Allows DAPT initiation up to 72 h in eligible mild stroke.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'chance-2',
    shortName: 'CHANCE-2',
    fullName: 'Ticagrelor or Clopidogrel with Aspirin in High-Risk TIA or Minor Stroke',
    topic: 'dapt-minor-stroke',
    diseaseArea: ['secondary-prevention', 'dapt-minor-stroke'],
    population: { n: 6412, ageRange: '≥40', nihssRange: 'NIHSS ≤3', timeWindow: '≤24 h', keyInclusion: ['CYP2C19 loss-of-function carrier', 'Mild AIS or high-risk TIA'], keyExclusion: [] },
    intervention: 'Ticagrelor + ASA x 21 d',
    comparator: 'Clopidogrel + ASA x 21 d',
    primaryEndpoint: { definition: 'New stroke at 90 d', timepoint: '90 d', result: 'Favored ticagrelor: 6.0% vs 7.6%', effectSize: 'HR 0.77', confidenceInterval: '95% CI 0.64 to 0.94', pValue: 'p=0.008' },
    secondaryEndpoints: [],
    safetyFindings: { sich: '', mortality: 'Similar', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Pharmacogenomic-guided antiplatelet strategy.',
    limitations: 'Genotype testing not always available.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-chance2-2021'],
    relatedActiveTrialIds: ['captiva'],
    practiceImpact: 'Supports ticagrelor over clopidogrel in CYP2C19 LOF carriers.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- AF anticoagulation timing -------------------
  t({
    id: 'elan',
    shortName: 'ELAN',
    fullName: 'Early versus Later Anticoagulation for Stroke with Atrial Fibrillation',
    topic: 'af-anticoag-timing',
    diseaseArea: ['secondary-prevention', 'af-anticoag-timing'],
    population: { n: 2013, ageRange: '≥18', nihssRange: 'all', timeWindow: 'post-AIS, ≤28 d', keyInclusion: ['AIS with non-valvular AF'], keyExclusion: ['Mechanical valve'] },
    intervention: 'Early DOAC (within 48 h for minor, 6-7 d for major)',
    comparator: 'Delayed DOAC (>3-4 d for minor, 12-14 d for major)',
    primaryEndpoint: { definition: 'Composite of recurrent stroke / SE / major bleeding at 30 d', timepoint: '30 d', result: 'Favored early', effectSize: 'OR 0.57', confidenceInterval: '95% CI 0.29 to 1.07', pValue: '' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Used stroke severity (CT-derived) to calibrate timing.',
    limitations: 'Confidence interval crosses 1 for primary; secondary supports early.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-elan-2023'],
    relatedActiveTrialIds: [],
    practiceImpact: 'Supports early DOAC initiation per stroke severity.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'timing',
    shortName: 'TIMING',
    fullName: 'Timing of Oral Anticoagulant Therapy in AIS with AF',
    topic: 'af-anticoag-timing',
    diseaseArea: ['secondary-prevention', 'af-anticoag-timing'],
    population: { n: 888, ageRange: '≥18', nihssRange: 'all', timeWindow: '≤72 h post-AIS', keyInclusion: ['AIS with non-valvular AF'], keyExclusion: [] },
    intervention: 'Early DOAC (≤4 d)',
    comparator: 'Delayed DOAC (5-10 d)',
    primaryEndpoint: { definition: 'Composite ischemic event / sICH / mortality at 90 d', timepoint: '90 d', result: 'Non-inferior favoring early', effectSize: 'Risk difference -2.5%', confidenceInterval: '95% CI -5.6 to +0.5', pValue: 'Non-inferiority met' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'No increase', mortality: 'Similar', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Smaller than ELAN; consistent direction.',
    limitations: 'Underpowered for superiority.',
    certainty: 'moderate',
    evidenceType: 'rct',
    citationIds: ['cit-timing-2022'],
    relatedActiveTrialIds: [],
    practiceImpact: 'Supports earlier DOAC initiation.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- AF prevention background -------------------
  t({
    id: 'averroes',
    shortName: 'AVERROES',
    fullName: 'Apixaban in Patients with Atrial Fibrillation Unsuitable for VKA',
    topic: 'af-after-ich',
    diseaseArea: ['secondary-prevention', 'af-after-ich'],
    population: { n: 5599, ageRange: '≥50', nihssRange: 'n/a', timeWindow: 'chronic AF', keyInclusion: ['AF with ≥1 stroke risk factor; not VKA candidate'], keyExclusion: [] },
    intervention: 'Apixaban 5 mg BID',
    comparator: 'Aspirin 81-324 mg/d',
    primaryEndpoint: { definition: 'Stroke or systemic embolism', timepoint: '~1 y', result: 'Favored apixaban: 1.6%/y vs 3.7%/y', effectSize: 'HR 0.45', confidenceInterval: '95% CI 0.32 to 0.62', pValue: 'p<0.001' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: 'Major bleeding similar' },
    imagingCriteria: '',
    applicabilityNotes: 'AF stroke prevention superiority of apixaban over aspirin in VKA-unsuitable patients.',
    limitations: 'Pre-DOAC adoption era; comparator is aspirin.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-averroes-2011'],
    relatedActiveTrialIds: ['aspire'],
    practiceImpact: 'Supports anticoagulation over aspirin for AF stroke prevention; informs ASPIRE rationale.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),
  t({
    id: 'artesia',
    shortName: 'ARTESiA',
    fullName: 'Apixaban for Stroke Prevention in Subclinical Atrial Fibrillation',
    topic: 'af-after-ich',
    diseaseArea: ['secondary-prevention', 'af-after-ich'],
    population: { n: 4012, ageRange: '≥55', nihssRange: 'n/a', timeWindow: 'subclinical AF detected on device', keyInclusion: ['Subclinical AF on cardiac implantable device'], keyExclusion: [] },
    intervention: 'Apixaban',
    comparator: 'Aspirin 81 mg',
    primaryEndpoint: { definition: 'Stroke or systemic embolism', timepoint: '3.5 y', result: 'Favored apixaban: 0.78%/y vs 1.24%/y', effectSize: 'HR 0.63', confidenceInterval: '95% CI 0.45 to 0.88', pValue: 'p=0.007' },
    secondaryEndpoints: [{ name: 'Major bleeding', result: '1.71%/y vs 0.94%/y; HR 1.80' }],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: 'Major bleeding higher with apixaban' },
    imagingCriteria: '',
    applicabilityNotes: 'Frame for ICH-survivor decisions: anticoagulation reduces stroke at the cost of bleeding.',
    limitations: 'Subclinical AF only.',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-artesia-2023'],
    relatedActiveTrialIds: ['aspire'],
    practiceImpact: 'Establishes apixaban benefit even in subclinical AF; informs ICH-survivor decisions.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  }),

  // ------------------- BP after EVT -------------------
  t({
    id: 'enchanted2-mt',
    shortName: 'ENCHANTED2/MT',
    fullName: 'Intensive BP Control after Endovascular Thrombectomy',
    topic: 'evt-late-window',
    diseaseArea: ['acute-ischemic-stroke', 'evt-late-window'],
    population: { n: 821, ageRange: '≥18', nihssRange: 'all', timeWindow: 'post-successful EVT', keyInclusion: ['Successful EVT with mTICI 2b/3'], keyExclusion: [] },
    intervention: 'Intensive SBP target 120-140 mmHg',
    comparator: 'Less-intensive SBP target 140-180 mmHg',
    primaryEndpoint: { definition: 'mRS shift at 90 d', timepoint: '90 d', result: 'Favored less-intensive (worse with intensive)', effectSize: 'OR 1.37', confidenceInterval: '95% CI 1.07 to 1.76', pValue: 'p=0.012' },
    secondaryEndpoints: [],
    safetyFindings: { sich: 'Similar', mortality: 'Similar', other: '' },
    imagingCriteria: '',
    applicabilityNotes: 'Post-EVT BP intensive lowering harmful; conventional control preferred.',
    limitations: 'Single-region trial (China).',
    certainty: 'high',
    evidenceType: 'rct',
    citationIds: ['cit-enchanted2-mt-2022'],
    relatedActiveTrialIds: [],
    practiceImpact: 'Avoid intensive BP lowering after successful EVT; target 140-180 mmHg.',
    lastReviewed: lr,
    verificationStatus: 'verified-pubmed'
  })
];

const byId = new Map(completedTrials.map((c) => [c.id, c]));

export function getCompletedTrial(id) {
  return byId.get(id) || null;
}

export function getAllCompletedTrialIds() {
  return new Set(byId.keys());
}
